services:
  frontend:
    build:
      context: .
      args:
        VITE_API_BASE_URL: http://backend:8000
    container_name: reserving-frontend
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Pass through if you want FE->BE calls in container:
      - VITE_API_BASE_URL=http://backend:8000
    ports:
      - "3001:3000"   # host:container
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: reserving-backend
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
